services:
  goodreads-scraper:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - CACHE_TTL=6h
      - SCRAPE_TIMEOUT=30s
      - LOG_LEVEL=info
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 